spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://caboose.proxy.rlwy.net:27648/cafesyncdb
    username: root
    password: IfTntyVIcASjJDhEBTyTWbkocSjzuEDW

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    hibernate:
      ddl-auto: update

  mybatis:
    mapper-locations: classpath:mappers/**/*.xml

  data:
    redis:
      host: redis.railway.internal
      port: 6379
      timeout : 5s
      password: ${REDIS_PASSWORD}

  jwt:
    secret: "${JWT_SECRET:default-secret-key-should-be-changed}"

  mail:
    host: smtp.gmail.com
    port: 587
    username: keunhee0920@gmail.com
    password: gzetusnosgwqjqri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true   # ✅ STARTTLS 활성화
            required: true # ✅ STARTTLS 필수 적용
        debug: true  # 디버깅 활성화 (개발용)
