spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafesyncdb
    username: cafesync
    password: cafesync

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  mybatis:
    mapper-locations: classpath:mappers/**/*.xml # MyBatis 매퍼 파일 위치