spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cafesyncdb
    username: cafesync
    password: cafesync

  jpa:
    show-sql: true
    database: mysql
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mybatis:
    mapper-locations: classpath:mappers/**/*.xml

  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout : 5s

  jwt:
    secret: "${JWT_SECRET:default-secret-key-should-be-changed}"

  mail:
    host: smtp.gmail.com
    port: 587
    username: keunhee0920@gmail.com
    password: gzetusnosgwqjqri
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true   # ✅ STARTTLS 활성화
            required: true # ✅ STARTTLS 필수 적용
        debug: true  # 디버깅 활성화 (개발용)
